In [1]:
import numpy as np
import pandas as pd

In [2]:
messages = pd.read_csv('smsspamcollection', sep='\t', names=["label", "message"])

In [3]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
import re
import nltk

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [10]:
nltk.download('stopwords')

corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])  #this is to remove full-stop, commas etc
    review = review.lower() #to lower every letter in sentence
    review = review.split() #to split 
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]  #stemming
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to C:\Users\Ujjval
[nltk_data]     Priyadarshi\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()

In [14]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [16]:
# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [19]:
y_test

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [20]:
y_pred

array([0, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [21]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score

conf_mat= confusion_matrix(y_test, y_pred)
accuracy= accuracy_score(y_test, y_pred)

In [22]:
conf_mat

array([[946,   9],
       [  7, 153]], dtype=int64)

In [23]:
accuracy

0.9856502242152466